-
    name: 'conditions_testing'
    hosts: localhost
    tasks:

      - name: Register a variable
        shell: cat /etc/hosts
        register: output

      - name: check file is empty
        command: echo "file is empty"
        when: output.stdout == ""
